# Generated by Django 3.0.7 on 2020-06-08 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='client',
        ),
        migrations.AddField(
            model_name='cdr',
            name='client',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='factureTelephonique.Client'),
            preserve_default=False,
        ),
    ]
