# Generated by Django 3.0.7 on 2020-06-08 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0002_auto_20200608_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factureTelephonique.Client'),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factureTelephonique.Client'),
        ),
    ]
