# Generated by Django 3.0.7 on 2020-06-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0003_auto_20200608_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdr',
            name='client',
        ),
    ]
