# Generated by Django 3.0.7 on 2020-06-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0005_cdr_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdr',
            name='client',
        ),
    ]
