# Generated by Django 3.0.7 on 2020-06-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0006_remove_cdr_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
