# Generated by Django 3.0.7 on 2020-06-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0007_auto_20200613_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
