# Generated by Django 3.0.7 on 2020-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0009_auto_20200627_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='dureeTotal',
            field=models.BigIntegerField(verbose_name='Durée total'),
        ),
    ]
