# Generated by Django 3.0.7 on 2020-06-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0010_auto_20200627_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='dureeTotal',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Durée total'),
        ),
    ]
