# Generated by Django 3.0.7 on 2020-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0011_auto_20200627_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='dureeTotal',
            field=models.TimeField(verbose_name='Durée total'),
        ),
    ]
