# Generated by Django 3.0.7 on 2020-06-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0013_auto_20200628_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='dureeTotal',
            field=models.TimeField(verbose_name='Durée total'),
        ),
    ]
