# Generated by Django 3.0.7 on 2020-06-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0014_auto_20200628_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='dureeAppel',
            field=models.CharField(max_length=20, verbose_name="durée de l'appel"),
        ),
    ]
