# Generated by Django 3.0.7 on 2020-06-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factureTelephonique', '0015_auto_20200630_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='dureeTotal',
            field=models.CharField(max_length=20, verbose_name='Durée total'),
        ),
    ]
